#! /usr/bin/ruby

require 'date'

date = Date.today.strftime
input = ARGV.join(' ')
timestamp = Time.now.strftime('%H:%M:%S')

if input.gsub(" ","") == ""
  raise "Usage: new_post <title>"
end

BASE_TEMPLATE = <<-TEMPLATE
---
layout: article
title: #{input}
date: #{date} #{timestamp}
categories: programming
tags:
- programming
---
TEMPLATE
filename = "#{date}-#{input.downcase.gsub(/\s+/,'-')}.md"
File.open(File.join("_posts", filename), "w+") do |f|
  f.write(BASE_TEMPLATE)
end
puts "Created new post: #{File.join("_posts", filename)}"
